### ISSUE TITLE
Add support for XDG_STATE_HOME in basedir

### ISSUE THREAD

**Issue by getawaywithrmdir** [rkoesters/xdg#15]
Could you add support for XDG_STATE_HOME in xdg/basedir? It was added to the XDG spec in 2022 (the basedir documentation link is correct and includes this). It's important as a place for logs, history, etc.—stuff that shouldn't go in cache (since it's not safe to delete if the app can't recreate it), nor in config or data (since these each include things you might want to sync across machines, which is usually undesirable with history).

I was trying to convince downstream projects to add support, but then realized it doesn't exist here...

Thanks in advance for your help! 🙏

**Comment by rkoesters** [comment]
Fixed by @MHNightCat in #16.
